name: Build and Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4.2.2
    - uses: actions/setup-python@v5.6.0
      with:
        python-version: '3.14'
          # cache: 'pipenv' # caching pipenv dependencies
    - name: Install uv and pipx
      run: |
        pip install uv && pip install pipx

    - name: Install global dependencies
      run: |
        pipx install isort && pipx install black && pipx install bandit && \
        pipx install pylint && pipx install pre-commit && pipx install uv

    - name: Install Dependencies
      run: uv sync

    - name: Run Makefile
      run: uv run make check
    - name: Run make
      run: uv run  make publish
    - name: Upload Package
      uses: actions/upload-artifact@v4.6.2
      with:
        name: packages
        path: dist/
        if-no-files-found: error
        retention-days: 1


  pypi-publish:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/bug-trail
    permissions:
      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing
    # if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    steps:
    - name: Get packages
      uses: actions/download-artifact@v4.3.0
      with:
        name: packages
        path: dist/
    - name: Publish package distributions to PyPI
      uses: pypa/gh-action-pypi-publish@v1.12.4
    needs: build
